name: task_tracker
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  flutter_svg: ^2.0.7
  go_router: ^10.1.2
  hive: ^2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: Anonymous Pro
      fonts:
        - asset: assets/fonts/AnonymousProBoldItalic.ttf
          weight: 700
        - asset: assets/fonts/AnonymousProBold.ttf
          weight: 700
        - asset: assets/fonts/AnonymousProItalic.ttf
          weight: 400
        - asset: assets/fonts/AnonymousProRegular.ttf
